name: post_scheduler
description: "Um aplicativo Flutter para agendamento de postagens em redes sociais"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  image_picker: ^1.0.4
  table_calendar: ^3.0.9
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  generate: true
